# Generated by Django 4.1 on 2022-08-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='persona',
        ),
    ]
