# Generated by Django 4.1 on 2022-08-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_rename_estudiante_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='persona',
            new_name='Individuo',
        ),
    ]
